# Generated by Django 4.1.4 on 2022-12-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqzfisio', '0002_agenda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='data',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(choices=[('SEGUNDA', 'segunda-feira'), ('TERCA', 'terça-feira'), ('QUARTA', 'quarta-feira'), ('QUINTA', 'quinta-feira'), ('SEXTA', 'sexta-feira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Maculino'), ('F', 'Feminino')], max_length=9),
        ),
    ]
